// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebApplication19.Entities
{
    public partial class Class
    {
        public Class()
        {
            Students = new HashSet<Students>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Students> Students { get; set; }
    }
}