// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebApplication19.Entities
{
    public partial class Students
    {
        public long Id { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public int Age { get; set; }
        public decimal? TotalFee { get; set; }
        public decimal? Paid { get; set; }
        public decimal? Due { get; set; }
        public long? ClassId { get; set; }
        public string Address { get; set; }
        public long AaadharNumber { get; set; }

        public virtual Class Class { get; set; }
    }
}